name: appdev
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.5
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.15.2
  firebase_core_web: ^2.9.0
  equatable: ^2.0.5
  fluttertoast: ^8.2.4
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.0

  sign_in_button: ^3.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/login.png
  - assets/register.png
  - assets/google.png