// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkUKZLFqhoI7XdVSSnSZX9rawQgZb0ZTQ',
    appId: '1:418689230859:web:db735cdb9d8afa45ee3f0e',
    messagingSenderId: '418689230859',
    projectId: 'appdev-832c2',
    authDomain: 'appdev-832c2.firebaseapp.com',
    storageBucket: 'appdev-832c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2iA-JXMbTmm8rIFY4D3VXtJG8zzkhxcQ',
    appId: '1:418689230859:android:09e15246b375fddeee3f0e',
    messagingSenderId: '418689230859',
    projectId: 'appdev-832c2',
    storageBucket: 'appdev-832c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo_oHM8wNBPVaGhSgckM2WTDtQq_gucEw',
    appId: '1:418689230859:ios:cdd89168bf7e91d5ee3f0e',
    messagingSenderId: '418689230859',
    projectId: 'appdev-832c2',
    storageBucket: 'appdev-832c2.appspot.com',
    androidClientId: '418689230859-5s04qhvceeju9ab26mnlp5j49c63h18o.apps.googleusercontent.com',
    iosClientId: '418689230859-unhfd7k1t0r1baak02ophjmpb2junb82.apps.googleusercontent.com',
    iosBundleId: 'com.example.appdev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo_oHM8wNBPVaGhSgckM2WTDtQq_gucEw',
    appId: '1:418689230859:ios:759d98bba414edcbee3f0e',
    messagingSenderId: '418689230859',
    projectId: 'appdev-832c2',
    storageBucket: 'appdev-832c2.appspot.com',
    androidClientId: '418689230859-5s04qhvceeju9ab26mnlp5j49c63h18o.apps.googleusercontent.com',
    iosClientId: '418689230859-uj2hmhdid9oimiqelfaht353lhujfgsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.appdev.RunnerTests',
  );
}
